### PR TITLE
desktop-files should be conformant with the XDG standard

### PR DESCRIPTION
**Pull request by besser82**
Fixes dektop-file-validate error: `value "Budgie;" for key "OnlyShowIn" in group "Desktop Entry" contains an unregistered value "Budgie"; values extending the format should start with "X-"`

### CODE REVIEW

**Comment by fossfreedom** [comment]
Does freedesktop control this?  Maybe it would be better to submit "Budgie" as an officially recognised name in a similar manner as GNOME, Unity etc etc.

**Comment by besser82** [comment]
Yes, it's controlled by freedesktop; but this change is needed to be compatible with distributions, that didn't pick-up this change, yet.

**Comment by besser82** [comment]
Cinnamon uses `X-Cinnamon` and MATE uses `X-MATE`, btw…

**Comment by ikeydoherty** [comment]
> to be compatible with distributions
Which? You've not mentioned.

**Comment by besser82** [comment]
In particular I'm talking about Fedora; I'm currently packaging budgie-desktop for inclusion in Fedora and to provide a new official Fedora-spin for it, starting with Fedora 27.

For Fedora packaging it is requires to run desktop-file-validate on the installed desktop-files; without this change it gives me the specified error…

**Comment by ikeydoherty** [comment]
I believe the correct approach here is to register ourselves upstream @ XDG

https://bugs.freedesktop.org/show_bug.cgi?id=100996
https://bugs.freedesktop.org/show_bug.cgi?id=100997

**Comment by ikeydoherty** [comment]
FWIW I'm not going to merge this PR unless the freedesktop people reject my patches.

**Comment by ikeydoherty** [comment]
Well upstream is completely unresponsive, which is more in their court than mine. Not going to change the names, sorry, especially when the standard involves an unresponsive organisation :)

**Pull request closed without merging**
