### PR TITLE
Add panel transparency controls

### PR DESCRIPTION
**Pull request by cybre**
This patch adds three modes of panel transparency:
 - None (The panel is always opaque)
 - Dynamic (The panel is opaque when there is a maximized window on the workspace or if raven is open, otherwise it's transparent)
 - Always (The panel is always transparent)

### CODE REVIEW

**Comment by ikeydoherty** [comment]
LGTM actually. Cheers lad :) Basically people should disable shadow if they're using dynamic panel transparency, from my stance (And I know you agree). Merging :)

**Comment by Vistaus** [comment]
Would it be possible to add controls to adjust the amount of tranparency? (or is there some other way to do that)

**Comment by ikeydoherty** [comment]
No - it's all done by CSS theming not Cairo

**Comment by Vistaus** [comment]
Sorry for deleting my comment - thought I'd move it into a new issue but you replied so fast :P 

Is there any way I can do it with CSS?

**Comment by ikeydoherty** [comment]
Well I mean it's controlled by the global GTK theme (or builtin-on) which has specific background-color style properties. You can locally override in `~/.local/share/gtk-3.0/gtk.css`

```
.budgie-panel {
    background-image: none;
    background-color: alpha(#someColour, 0.7);
}
```

**Comment by Vistaus** [comment]
That's helpful, thanks :) But how do I define the amount of transparency with that code?

**Comment by ikeydoherty** [comment]
That `0.7` is 70% transparent

**Comment by Vistaus** [comment]
Ah, I see, thanks! :)

**Comment by ikeydoherty** [comment]
GTK styling is a bitch. :P

**Comment by Vistaus** [comment]
Hmm, it doesn't change any of the transparency of the panel of the built-in theme, nor does it add any with a 3rd-party theme :/

**Pull request merged**
