### PR TITLE
add traditional Chinese (Taiwan) translation

### PR DESCRIPTION
**Pull request by zerng07**
Hi everyone,

I have translated traditional Chinese (Taiwan) language translation, and here is the po file.

Thanks!

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Sorry we can only accept translations through Transifex itself, and not through Pull Requests.
Please see https://www.transifex.com/budgie-desktop/budgie-desktop/dashboard/

**Comment by zerng07** [comment]
By the way, we don't use "Chinese Traditional" language (which is "zh-Hant" and used for webstie mostly) on Linux. 

So "Chinese Traditional" language on Transifex could be deleted, and leaving only "Chinese (Taiwan)" language suggested.

**Comment by ikeydoherty** [comment]
I only accept the language requests that people create and translate, I don't choose them :)

**Comment by zerng07** [comment]
OK, that's fine. 
Just having one more language which won't be used on Linux. ;P

**Comment by ikeydoherty** [comment]
True =) Lots of unused languages on transifex I imagine :)

**Pull request closed without merging**
