### PR TITLE
Updating Budgie photo examples to their Solus 3 defaults

### PR DESCRIPTION
**Pull request by bhajneet**
modified:   .github/screenshots/MainMenu.png
modified:   .github/screenshots/Notification.png
modified:   .github/screenshots/Polkit.png
modified:   .github/screenshots/Raven_Settings.png
modified:   .github/screenshots/RunDialog.png

### CODE REVIEW

**Comment by ikeydoherty** [comment]
The filename is invalid as its no longer "Raven Settings". Also that Budgie icon on the menu isn't standard :D

**Comment by bhajneet** [comment]
Okay, I booted up the liveUSB with the time set to 06:30, resolution at 1920x1080, and wallpaper from iceland to do the desktop, raven, and budgie menu.

I left the rest at 2560x1440, but let me know if you'd like them changed.

I also combined the Raven Applet's screenshot with the mpris to show the applet's and media control at the same time.

When I started, I didn't realize I had changed the wallpaper from it's default rock formation to the iceland one, so let me know if you want me to re-do them with that as the bg.

**Comment by bhajneet** [comment]
I updated the links to use relative paths, so you can visually see the changes in the readme when you click "view".

**Comment by ikeydoherty** [comment]
Sorry this'll need redoing due to the conflicting PR, and they'd need compressing. Probably we'll end up removing the screenshots and only have them on the website.

**Pull request closed without merging**
