### PR TITLE
ensure budgie-desktop-settings.desktop WMClass matches the value set in code

### LINKED ISSUE #1146: Opening and Closing Budgie Settings Leaves Ominous “Budgie Panel” Icon In Plank
### Steps to reproduce

*  Download the [latest Ubuntu Budige 17.10 Build](http://cdimage.ubuntu.com/ubuntu-budgie/daily-live/current/HEADER.html) and run a live session
 * Open Raven and click on the cog to open Budgie Settings
 * Close the Budgie Settings Window
 * An icon stays at the bottom of Plank. Its title is “Budgie Panel”. Neither clicking on it nor right clicking on it and hitting “close” has any apparent effect. It will stay there until `budgie-panel` is restarted (e.g. by `killall budgie-panel`)

budgie panel icon

**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.4

### PR DESCRIPTION
**Pull request by fossfreedom**
finally resolves #1146

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Sorry to be nitpicky here but can you provide a well formatted commit message? With proper capitalization, subject fitting < 80 chars, etc. Thanks. :)

**Comment by ikeydoherty** [comment]
(Just force push so its the one commit)

**Comment by fossfreedom** [comment]
sure! better ?

**Comment by ikeydoherty** [comment]
Perfect thanks, meant to merge quicker but inbox is going off the wall right now ^^

**Pull request merged**
