### PR TITLE
add style for GtkMenuBar and related objects

### PR DESCRIPTION
**Pull request by fossfreedom**
ok - have made an attempt here to add some styling for GtkMenu based applets.  Would appreciate some thoughts and help please.

Note - the PR is just for the _main.scss changes - I havent included the full gulp compiled css files.

For such applets applying the new style-class budgie-menubar is enough to style the applet correctly when using the system theme.  Tested via my applet budgie-indicator-applet, and also the global menu applet.

The global menu applet at the moment does have an issue - the applet loses the new style class when switching between applications.  The maintainer is going to have a look.

I couldn't get the theming to work correctly without this new style class - existing Raven objects were affected.

ubuntu xenial dev running - oracle vm virtualbox 1_015

### CODE REVIEW

**Comment by ikeydoherty** [comment]
I might be wrong but it looks like shadows are broken?

**Comment by fossfreedom** [comment]
hmm. yep.  Although no idea how to resolve.  

I threw around "&.background { @extend .drop-shadow; }" type statements - no effect.  just wondering if box-shadows actually apply to GtkMenu's or is there some other trick here I'm missing.

**Comment by fossfreedom** [comment]
ubuntu budgie - new development running - oracle vm virtualbox_016

okey-dokey - now have shadows.

**Comment by ikeydoherty** [comment]
I may opt to make that slightly less transparent but lets merge it, cheers

**Pull request merged**
