### PR TITLE
Added ability to Shift click on an icon to launch a new instance

### PR DESCRIPTION
**Pull request by okabeR**
As the title says: Added ability to Shift click on an icon to launch a new instance.

### CODE REVIEW

**Comment by fossfreedom** [comment]
just a casual observer - the formatting seems to have gone awry. Suggest run ./update-format.sh that is available in the root.

**Comment by okabeR** [comment]
@fossfreedom Thanks for the tip. Tried running ./update-format.sh but it didn't do much. Tried to fix the formatting best I could by hand.

**Comment by ikeydoherty** [comment]
This looks completely janked - please ensure you have `clang-format` installed (and optionally `misspell`) - this will also need rebasing too sorry

**Comment by cybre** [comment]
You can launch a new instance of an app by middle-clicking the icon in the new icon taklist (merged in https://github.com/budgie-desktop/budgie-desktop/pull/1364)

**Comment by okabeR** [comment]
@cybre I agree. This can be closed since #1364 accomplishes what I was trying to do.

**Pull request closed without merging**
